import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Appbar } from "@/src/widgets";
import { QueryProvider } from "@/src/shared";

const nanumSquare = localFont({
	src: [
		{
			path: "../public/fonts/NanumSquareR.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "../public/fonts/NanumSquareB.ttf",
			weight: "700",
			style: "normal",
		},
		{
			path: "../public/fonts/NanumSquareEB.ttf",
			weight: "800",
			style: "normal",
		},
	],
});

export const metadata: Metadata = {
	title: "이동규 - 코드잇 스프린트 사전 과제",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<QueryProvider>
			<html
				lang="en"
				className={`${nanumSquare.className} h-full antialiased bg-gray-50`}
			>
				<body className="flex flex-col items-center h-full">
					<Appbar />
					<main className="mt-(--header-height) w-full h-full max-w-300">
						{children}
					</main>
				</body>
			</html>
		</QueryProvider>
	);
}
